### ISSUE TITLE
System.IO.FileLoadException

### ISSUE THREAD

**Issue by ZeWaka** [tgstation/IconDiffBot#60] opened 2020-04-03 18:04 UTC
```
System.IO.FileLoadException: Could not load file or assembly 'MetadataExtractor, Version=2.2.0.0, Culture=neutral, PublicKeyToken=null'. The located assembly's manifest definition does not match the assembly reference. (Exception from HRESULT: 0x80131040)
File name: 'MetadataExtractor, Version=2.2.0.0, Culture=neutral, PublicKeyToken=null'
   at IconDiffBot.Core.DiffGenerator.StreamToMetadataString(Stream stream)
   at IconDiffBot.Core.DiffGenerator.GenerateDiffs(Stream before, Stream after)
   at IconDiffBot.Core.PayloadProcessor.<>c__DisplayClass12_0.<<GenerateDiffs>g__DiffDmi|0>d.MoveNext()
```
a) The commit that caused the failure
https://github.com/goonstation/goonstation/pull/78/commits/779bc0ac2524f777ab58f88571c46988353f037b

b) The failed check run
https://github.com/goonstation/goonstation/pull/78/checks?check_run_id=557732022

Cannot rerun job either, as it was 'passing.'

**Comment by Cyberboss** [comment] 2020-04-03 18:48
Can you try re-pushing the commit?
```
git commit --amend --no-edit
git push -f
```

**Comment by ZeWaka** [comment] 2020-04-03 18:52
Well, I don't think the commit/file is what caused it, but can do so. Would be nice if the error was caught and reported as a failure so the job could be re-run.

Edit: Couldn't figure out how to re-push, as it wasn't my own PR.

**Comment by Cyberboss** [comment] 2020-04-04 02:46
Pretty sure this is just because @AffectedArc07 was updating the bot.

Duplicate of #59

**Closed as completed by Cyberboss** 2020-04-04 02:46 UTC
